spring:
  profiles.active: dev
  thymeleaf.cache: false
  jpa.hibernate.ddl-auto: ""
  data.jpa.repositories.enabled: true
  jpa.show-sql: true
  http.encoding.charset: UTF-8

security:
  basic.enabled: false

server:
  tomcat.uri-encoding: UTF-8

login:
  passwordError: 两次密码输入不一致
  captchaError: 请输入正确的验证码
  oldPasswordError: 原密码错误

---
spring:
  profiles: dev
  redis.host: 192.168.1.137
  redis.port: 6379
  data.elasticsearch.cluster-nodes: 192.168.1.137:9300

logging:
  level.org.springframework.web: INFO
  level.org.springframework.security: DEBUG
  level.org.hibernate.type: INFO
---
spring:
   profiles: prod

logging:
  level.org.springframework.web: INFO
  level.org.springframework.security: INFO