spring:
  profiles.active: dev
  thymeleaf.cache: false
  jpa.hibernate.ddl-auto: ""
  data.jpa.repositories.enabled: true
  jpa.show-sql: true
  http.encoding.charset: UTF-8

security:
  basic.enabled: false

server:
  tomcat.uri-encoding: UTF-8

login:
  passwordError: 两次密码输入不一致
  captchaError: 请输入正确的验证码
  oldPasswordError: 原密码错误

---
spring:
  profiles: dev

logging:
  level.org.springframework.web: DEBUG
  level.org.springframework.security: INFO
  level.org.hibernate.type: TRACE
---
spring:
   profiles: prod

logging:
  level.org.springframework.web: INFO
  level.org.springframework.security: INFO