spring:
  profiles.active: prod
  thymeleaf.cache: false
  data.jpa.repositories.enabled: true
  http.encoding.charset: UTF-8
  jpa:
    show-sql: true
    hibernate:
      dll-auto: none


security:
  basic.enabled: false

server:
  tomcat.uri-encoding: UTF-8
  port: 8090

multipart:
        maxFileSize: -1
        maxRequestSize: -1

login:
  passwordError: 两次密码输入不一致
  captchaError: 请输入正确的验证码
  oldPasswordError: 原密码错误

---
spring:
  profiles: dev

logging:
  level.org.springframework.web: INFO
  level.org.springframework.security: INFO
  level.org.hibernate.type: TRACE
---
spring:
   profiles: prod
   datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sj
        username: root
        password: 1234
        initialize: false
   jpa:
     properties:
       hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level.org.springframework.web: INFO
  level.org.springframework.security: INFO