package com.sj.model.type;

public enum OutputEnum {
	FOLLOWINGFIVEMILLION,			//五百万以下
	FIVEMILLIONTOTWENTYMILLION,		//五百万至2000万
	TWENTYMILLIONTOFIFTYMILLION,	//2000万至5000万
	FIFTYMILLIONTOONEHUBDREDMILLION,//5000万至一亿
	ONEHUBDREDMILLIONTOFIVE,		//一亿至五亿
	MORETHANFIVEHUBDREDMILLION		//五亿以上
}
